name: CI-CD

on:
  pull_request:
    branches:
      - develop
      - main
      - feature/taller-devops
  push:
    branches:
      - develop
      - feature/taller-devops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Construcción del proyecto
        run: cd src && mvn clean package
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: src/target/*.jar